[tool.commitizen]
version = "1.0.0"  # This should be your current semver version
name = "cz_jira"
tag_format = "$version"
version_scheme = "semver"
version_provider = "npm"
update_changelog_on_bump = true
major_version_zero = true
